# Generated by Django 2.1.2 on 2019-03-19 10:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('priority', models.IntegerField()),
                ('assumed_time', models.FloatField()),
                ('applied_time', models.FloatField(null=True)),
                ('color', models.IntegerField(choices=[(1, 'blue'), (2, 'green'), (3, 'red'), (4, 'yellow'), (5, 'violet')])),
            ],
            options={
                'ordering': ('plan_id', '-priority'),
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('start_time', models.TimeField(choices=[(0, datetime.timedelta(0)), (1, datetime.timedelta(0, 1800)), (2, datetime.timedelta(0, 3600)), (3, datetime.timedelta(0, 5400)), (4, datetime.timedelta(0, 7200)), (5, datetime.timedelta(0, 9000)), (6, datetime.timedelta(0, 10800)), (7, datetime.timedelta(0, 12600)), (8, datetime.timedelta(0, 14400)), (9, datetime.timedelta(0, 16200)), (10, datetime.timedelta(0, 18000)), (11, datetime.timedelta(0, 19800)), (12, datetime.timedelta(0, 21600)), (13, datetime.timedelta(0, 23400)), (14, datetime.timedelta(0, 25200)), (15, datetime.timedelta(0, 27000)), (16, datetime.timedelta(0, 28800)), (17, datetime.timedelta(0, 30600)), (18, datetime.timedelta(0, 32400)), (19, datetime.timedelta(0, 34200)), (20, datetime.timedelta(0, 36000)), (21, datetime.timedelta(0, 37800)), (22, datetime.timedelta(0, 39600)), (23, datetime.timedelta(0, 41400)), (24, datetime.timedelta(0, 43200)), (25, datetime.timedelta(0, 45000)), (26, datetime.timedelta(0, 46800)), (27, datetime.timedelta(0, 48600)), (28, datetime.timedelta(0, 50400)), (29, datetime.timedelta(0, 52200)), (30, datetime.timedelta(0, 54000)), (31, datetime.timedelta(0, 55800)), (32, datetime.timedelta(0, 57600)), (33, datetime.timedelta(0, 59400)), (34, datetime.timedelta(0, 61200)), (35, datetime.timedelta(0, 63000)), (36, datetime.timedelta(0, 64800)), (37, datetime.timedelta(0, 66600)), (38, datetime.timedelta(0, 68400)), (39, datetime.timedelta(0, 70200)), (40, datetime.timedelta(0, 72000)), (41, datetime.timedelta(0, 73800)), (42, datetime.timedelta(0, 75600)), (43, datetime.timedelta(0, 77400)), (44, datetime.timedelta(0, 79200)), (45, datetime.timedelta(0, 81000)), (46, datetime.timedelta(0, 82800)), (47, datetime.timedelta(0, 84600))])),
                ('end_time', models.TimeField(choices=[(0, datetime.timedelta(0)), (1, datetime.timedelta(0, 1800)), (2, datetime.timedelta(0, 3600)), (3, datetime.timedelta(0, 5400)), (4, datetime.timedelta(0, 7200)), (5, datetime.timedelta(0, 9000)), (6, datetime.timedelta(0, 10800)), (7, datetime.timedelta(0, 12600)), (8, datetime.timedelta(0, 14400)), (9, datetime.timedelta(0, 16200)), (10, datetime.timedelta(0, 18000)), (11, datetime.timedelta(0, 19800)), (12, datetime.timedelta(0, 21600)), (13, datetime.timedelta(0, 23400)), (14, datetime.timedelta(0, 25200)), (15, datetime.timedelta(0, 27000)), (16, datetime.timedelta(0, 28800)), (17, datetime.timedelta(0, 30600)), (18, datetime.timedelta(0, 32400)), (19, datetime.timedelta(0, 34200)), (20, datetime.timedelta(0, 36000)), (21, datetime.timedelta(0, 37800)), (22, datetime.timedelta(0, 39600)), (23, datetime.timedelta(0, 41400)), (24, datetime.timedelta(0, 43200)), (25, datetime.timedelta(0, 45000)), (26, datetime.timedelta(0, 46800)), (27, datetime.timedelta(0, 48600)), (28, datetime.timedelta(0, 50400)), (29, datetime.timedelta(0, 52200)), (30, datetime.timedelta(0, 54000)), (31, datetime.timedelta(0, 55800)), (32, datetime.timedelta(0, 57600)), (33, datetime.timedelta(0, 59400)), (34, datetime.timedelta(0, 61200)), (35, datetime.timedelta(0, 63000)), (36, datetime.timedelta(0, 64800)), (37, datetime.timedelta(0, 66600)), (38, datetime.timedelta(0, 68400)), (39, datetime.timedelta(0, 70200)), (40, datetime.timedelta(0, 72000)), (41, datetime.timedelta(0, 73800)), (42, datetime.timedelta(0, 75600)), (43, datetime.timedelta(0, 77400)), (44, datetime.timedelta(0, 79200)), (45, datetime.timedelta(0, 81000)), (46, datetime.timedelta(0, 82800)), (47, datetime.timedelta(0, 84600))])),
                ('duration', models.FloatField()),
            ],
            options={
                'ordering': ('plan_id', 'day', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('duration', models.FloatField()),
                ('execution', models.FloatField(null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Activities')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Plan')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Availability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Plan'),
        ),
        migrations.AddField(
            model_name='availability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activities',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Plan'),
        ),
        migrations.AddField(
            model_name='activities',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
