# Generated by Django 2.1.2 on 2019-03-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
