# Generated by Django 2.1.2 on 2019-03-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190319_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={},
        ),
        migrations.RemoveField(
            model_name='availability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start_time',
        ),
    ]
