# Generated by Django 2.1.2 on 2019-03-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190319_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='duration',
            field=models.FloatField(),
        ),
    ]
